# Generated by Django 2.1 on 2018-10-13 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedDelivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('days_minimum', models.IntegerField(blank=True, null=True)),
                ('days_maximum', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MethodClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_rate_calculation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Flat Rate', 'Flat Rate'), ('Free Shipping', 'Free Shipping'), ('Local Pickup', 'Local Pickup')], default='Flat Rate', max_length=200)),
                ('name', models.CharField(max_length=64, null=True)),
                ('free_shipping_requirements', models.CharField(choices=[('N/A', 'N/A'), ('Free Shipping Coupon', 'Free Shipping Coupon'), ('Minimum Order Amount', 'Minimum Order Amount'), ('Minimum Order Amount OR Coupon', 'Minimum Order Amount OR Coupon'), ('Minimum Order Amount AND Coupon', 'Minimum Order Amount AND Coupon')], default='N/A', max_length=200)),
                ('minimum_order', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_status', models.CharField(choices=[('None', 'None'), ('Taxable', 'Taxable')], default='None', max_length=200)),
                ('local_pickup_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('flat_rate_calculation', models.CharField(blank=True, max_length=200, null=True)),
                ('calculation_type', models.CharField(choices=[('Per item', 'Per item'), ('Most expensive shipping category', 'Most expensive shipping category')], default='Per item', max_length=200)),
                ('estimated_delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_delivery_method', to='shipping.EstimatedDelivery')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('regions', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_method', to='shipping.ShippingZone'),
        ),
        migrations.AddField(
            model_name='shippingclass',
            name='shipping_method',
            field=models.ManyToManyField(blank=True, related_name='shipping_class', through='shipping.MethodClass', to='shipping.ShippingMethod'),
        ),
        migrations.AddField(
            model_name='methodclass',
            name='shipping_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_class', to='shipping.ShippingClass'),
        ),
        migrations.AddField(
            model_name='methodclass',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='method_class', to='shipping.ShippingMethod'),
        ),
    ]
