# Generated by Django 2.1 on 2018-10-13 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='images.Image'),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='enable_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productpost',
            name='enable_reviews',
            field=models.BooleanField(default=True),
        ),
    ]
