# Generated by Django 2.1 on 2018-10-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0004_auto_20181014_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='attribute', to='product_catalogue.Product'),
        ),
    ]
