# Generated by Django 2.1 on 2018-10-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0005_attribute_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='attribute_value', to='product_catalogue.ProductPost'),
        ),
    ]
