# Generated by Django 2.1 on 2018-10-19 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0008_auto_20181019_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribute_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product_catalogue.AttributeValue'),
        ),
    ]
