# Generated by Django 2.1 on 2018-10-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0010_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reviewhelpfulness',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
    ]
