# Generated by Django 2.1 on 2018-11-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_catalogue', '0011_auto_20181028_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
